import Footer from "../containers/Footer";
import NavBar from "../containers/NavBar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Footer />
      <body>{children}</body>
      <NavBar />
    </html>
  );
}
